language: 
 - cpp

compiler: 
 - gcc
  
before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
 - sudo apt-get install qt5-default qttools5-dev-tools
 - sudo apt-get install g++-4.8
 
# before_script:
  # - mkdir build
  # - cd build
  # - cmake ..
   
script:
 - cd QtReports/QtReports
 - qmake -project
 - qmake qtreports.pro
 - make
 
#  notifications:
#  email: 
#    - xxx@users.sourceforge.net
#   on_success: change
#   on_failure: always
