language: cpp

os:
  - linux
  
compiler: 
  - gcc
  - clang
  
env:
  - BUILD_TYPE=release
# - BUILD_TYPE=debug
  
#env:
#  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
#   - secure: "P9gHn+wkHWzjRqcwlcCoSGmz8pw1aG3CwuPP0rsMpqsa+jh0lr3SDfdA01Xll68Rb7xY7yVTtXaFOXrEk6ceb3fvGs4JxYXNXRgkG8uF808Lm19bbADAQBb5kXECiClaLKk20es/Y4mlI6G/8Qmr4OmOc0Z2gL/sVqLnh6QLTtI="

  
matrix:
  include:
   - os: linux
     compiler: gcc
     env: BUILD_TYPE=coverage

#sudo: false
  
cache:
  apt: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/http
    - /home/travis/.cache/pip
    - /home/travis/.cache/pip/http
    - /var/cache/apt/archives/

branches:
  only:
    - master
    - develop
    - /^.*travis.*$/
    
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cc85956a4a2f1ab871d1
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

#addons:
#  apt:
#    sources:
#    - ubuntu-toolchain-r-test
#    - ubuntu-sdk-team
#    packages:
#    - gcc-4.8
#    - g++-4.8
#    - clang
#    - qt5-default

before_install:
  - sudo sh .travis/${TRAVIS_OS_NAME}/before_install.sh
  - sudo sh .travis/${TRAVIS_OS_NAME}/${CC}/before_install.sh
 
install:
#  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8" GCOV="gcov-4.8"; fi
  - source .travis/${TRAVIS_OS_NAME}/install.sh
  - source .travis/${TRAVIS_OS_NAME}/${CC}/install.sh
   
script:
  - nproc
  - g++ --version
  - gcov --version
  - cd qtreportslib
  - qmake -spec ${USING_QT_MKSPEC} "CONFIG+= ${BUILD_TYPE}" qtreportslib.pro
  - sudo make -j$(nproc)
  - sudo make install
  - cd ../qtreportsviewer
  - qmake -spec ${USING_QT_MKSPEC} qtreportsviewer.pro
  - make
  - cd ../tests/qtreportslib_tests
  - qmake -spec ${USING_QT_MKSPEC} "CONFIG+= ${BUILD_TYPE}" qtreportslib_tests.pro
  - sudo make
  - ./qtreportslib_tests
  - >
    if [ "$BUILD_TYPE" = "coverage" ]; then
      cd ../..
      sudo apt-get install tree
      tree
      cd qtreportslib
      sudo make coverage
    fi

after_success:
#  - if [ "$BUILD_TYPE" = "Coverage" ]; then ~/.local/bin/coveralls --repo_token "${COVERALLS_IO_TOKEN}" --gcov "$GCOV" --exclude build/gtest -E ".*CMake.*CompilerId.c" --gcov-options "\-lp" -r ../; fi
#  - if [ "$BUILD_TYPE" = "coverage" ]; then sudo ~/.local/bin/coveralls --repo_token "${COVERALLS_IO_TOKEN}" --gcov "gcov-4.8" --gcov-options "\-lp" -r ../../qtreportslib; fi
#  - if [ "$BUILD_TYPE" = "coverage" ]; then coveralls-lcov --repo_token "${COVERALLS_IO_TOKEN}" ../../qtreportslib/qtreportslib.cov; fi
  - > 
    if [ "$BUILD_TYPE" = "coverage" ]; then
      lcoveralls --retry-count 5 $TRAVIS_BUILD_DIR/qtreportslib/coverage.info 
    fi