language: cpp

compiler: 
  - gcc
  - clang

os:
  - linux
  
#sudo: false
  
cache:
  apt: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/http
    - /home/travis/.cache/pip
    - /home/travis/.cache/pip/http
    - /var/cache/apt/archives/

branches:
  only:
    - master
    - develop
    - /^.*travis.*$/
    
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cc85956a4a2f1ab871d1
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

#addons:
#  apt:
#    sources:
#    - ubuntu-toolchain-r-test
#    - ubuntu-sdk-team
#    packages:
#    - gcc-4.8
#    - g++-4.8
#    - clang
#    - qt5-default
  
#env:
#  matrix:
#    - BUILD_TYPE=Debug
#    - BUILD_TYPE=Release
#    - BUILD_TYPE=Coverage

before_install:
  - sudo sh .travis/${TRAVIS_OS_NAME}/before_install.sh || :
  - sudo sh .travis/${TRAVIS_OS_NAME}/${CC}/before_install.sh || :
 
install:
#  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8" GCOV="gcov-4.8"; fi
  - source .travis/${TRAVIS_OS_NAME}/install.sh || :
  - source .travis/${TRAVIS_OS_NAME}/${CC}/install.sh || :
   
# before_script:
#  - mkdir -p build
#  - cd build
#  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_PREFIX_PATH=${DEPS_PREFIX_PATH}
  
script:
  - cd qtreportslib
  - qmake -spec ${USING_QT_MKSPEC} qtreportslib.pro
  - make
  - cd ../qtreportsviewer
  - qmake -spec ${USING_QT_MKSPEC} qtreportsviewer.pro
  - make
#  - cmake --build . --target all -- --keep-going
#  - cmake --build . --target check

after_success:
  - if [ "$BUILD_TYPE" == "Coverage" ]; then ~/.local/bin/coveralls --repo_token "${COVERALLS_IO_TOKEN}" --gcov "$GCOV" --exclude build/gtest -E ".*CMake.*CompilerId.c" --gcov-options "\-lp" -r ../; fi
